openapi: 3.1.3
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Enter your JWT token
  schemas: {}
info:
  title: Spiceflow Documentation
  description: Development documentation
  version: 0.0.0
paths:
  /:
    get:
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
        default:
          description: ''
          content:
            text/plain:
              schema: {}
      operationId: getIndex
  /stream:
    get:
      x-fern-streaming:
        format: sse
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                  timestamp:
                    type: number
                required:
                  - count
                  - timestamp
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
        default:
          description: ''
          content:
            text/plain:
              schema: {}
      operationId: getStream
  /users/{id}:
    get:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
        default:
          description: ''
          content:
            text/plain:
              schema: {}
      operationId: getUsersById
  /users:
    post:
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data: {}
                required:
                  - message
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
        default:
          description: ''
          content:
            text/plain:
              schema: {}
      operationId: postUsers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                age:
                  type: number
                  minimum: 0
                  maximum: 120
              required:
                - name
                - email
                - age
              additionalProperties: false
  /openapi:
    get:
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema: {}
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                type: string
        default:
          description: ''
          content:
            text/plain:
              schema: {}
      operationId: getOpenapi
