openapi: 3.1.3
info:
  title: Spiceflow Documentation
  description: Development documentation
  version: 0.0.0
paths:
  /:
    get:
      operationId: getIndex
  /stream:
    get:
      x-fern-streaming:
        format: sse
      responses:
        '200':
          $schema: http://json-schema.org/draft-07/schema#
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                  timestamp:
                    type: number
                required:
                  - count
                  - timestamp
      operationId: getStream
  /users/{id}:
    get:
      parameters:
        - schema:
            type: string
          in: path
          name: id
          required: true
      operationId: getUsersById
  /users:
    post:
      parameters: []
      responses:
        '200':
          $schema: http://json-schema.org/draft-07/schema#
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data: {}
                required:
                  - message
      operationId: postUsers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                age:
                  type: number
                  minimum: 0
                  maximum: 120
              required:
                - name
                - email
                - age
              additionalProperties: false
              $schema: http://json-schema.org/draft-07/schema#
  /openapi:
    get:
      operationId: getOpenapi
components:
  schemas: {}
