#:schema node_modules/wrangler/config-schema.json
name = "spiceflow-website-worker"

assets = { directory = "build/client/assets/", binding = "ASSETS"  }

compatibility_date = "2025-01-01"

main = "./workers/app.ts"
